// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsdwrnwmqcrodgkrwzsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZHdybndtcWNyb2Rna3J3enN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTI1OTgsImV4cCI6MjA2MzI2ODU5OH0.usK82-_J4ShMsR9_GpMZfBJN7mBMQyqwo3uoufXpTmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);